### ISSUE TITLE
Future✨

### ISSUE THREAD

**Issue by aic-6301** [YurakunD3suyo/YuranuBot-Linux#2]
- [ ]  プチプチと音が鳴ってしまう問題
- [x] ほかのチャンネルのものがすべて流れてしまう問題
- [x] メッセージキューの作成(順番に処理させるため)
- [x] Skip機能(長文対策)
- [x] メンションをidではなく名前で読み上げ
- [x] 絵文字を省略
- [x] リンクを省略

**Comment by YuranuDev** [comment]
- [x] 速度向上
- [ ] 辞書機能
- [x] ！！！！チャンネルを絞る機能
- [ ] 自動接続の実装

**Comment by YuranuDev** [comment]
致命的な問題は解決したため、Issueを閉じます

**Comment by aic-6301** [comment]
ぜんぶおわったらとじてみよ？
